### ISSUE TITLE
Receiving 'FileNotFoundError: [Errno 2] No such file or directory: Error

### ISSUE THREAD

**Issue by RennisDitchie** [putnam/binmerge#11]
Hey there,

I found your utility via a 'gotbletu' video on YouTube:
https://www.youtube.com/watch?v=eJOO5tpWZU0

My current issue is that I am trying to merge two separate .bin files that were ripped for the "Dynasty Warriors 2" game into 1 .bin using the available .cue file present.

It appears to be erroring out on Line 98 where you are obtaining the size of the file itself using the 'os' library.

I am getting this error on a box using Fedora Server for reference.

Here's the output:
```
sam@fedoraserver ~/utilities/binmerge $ ls
 binmerge  'Dynasty Warriors 2.cue'  'Dynasty Warriors 2 (Track 1).bin'  'Dynasty Warriors 2 (Track 2).bin'   LICENSE   README.md
sam@fedoraserver ~/utilities/binmerge $ ./binmerge 'Dynasty Warriors 2.cue' 'Dynasty Warriors 2'
[INFO]  Opening cue: Dynasty Warriors 2.cue
Traceback (most recent call last):
  File "/home/sam/utilities/binmerge/./binmerge", line 306, in <module>
    if not main():
  File "/home/sam/utilities/binmerge/./binmerge", line 266, in main
    cue_map = read_cue_file(args.cuefile)
  File "/home/sam/utilities/binmerge/./binmerge", line 109, in read_cue_file
    this_file = File(os.path.join(os.path.dirname(cue_path), m.group(1)))
  File "/home/sam/utilities/binmerge/./binmerge", line 98, in __init__
    self.size = os.path.getsize(filename)
  File "/usr/lib64/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'Dynasty Warriors 2 (USA) (Track 1).bin'
```

Thanks for the utility, looks cool!

**Comment by putnam** [comment]
Your cue sheet expects the bin files to have (USA) in their names. You can
either edit the cue sheet to point at the right files or fix your bin
filenames. Let me know if that works!

**Comment by putnam** [comment]
I've added additional error handling so this isn't just an ugly stack trace. You'll still need to fix your cue sheet or your bin filenames, but binmerge's output might make more sense now. Please update to 1.0.1 on the release page.

**Comment by putnam** [comment]
No update from OP, closing
