### ISSUE TITLE
Option to not add full path to cue sheet when using --split

### ISSUE THREAD

**Issue by malvarenga123** [putnam/binmerge#12]
The issue was with my batch files.

**Comment by putnam** [comment]
Currently, the generation of the filenames is based on what you input to the program. It's a result of calling it with explicit full paths, rather than relative. You could maybe change directory before running it?

I could also see about adding some flag if it would improve the user experience. Can you clarify what your workflow looks like?

**Comment by putnam** [comment]
Just saw your edit -- it could still be an opportunity for improvement. Can you post your batch?

**Comment by malvarenga123** [comment]
Sorry for the late reply. The batch file was simple

`start "" /low %binmerge_path% --split %cue_name% %split_name%`

%split_name% had the full path. After changing it to %~dpn1 it worked fine.

**Comment by IceLancerSR** [comment]
for /r %%i in (*.cue) do binmerge --split "%%i" "%%~ni-original"

Much simpler version of batch
Thanks for the tool!

**Comment by MestreLion** [comment]
> You could maybe change directory before running it?

This a good workaround, but not the best solution. How the output files are specified should not change the output CUE _content_.

Not adding paths to the BIN files in the CUE content is quite a consensus in communities that deal with CUE files, so I believe no additional flag is necessary, and this can be default behavior.

As for implementation, a simple `os.path.basename(track_fn)` when creating the CUE content is enough. I can happily provide a PR if you're interested

**Comment by putnam** [comment]
Yeah, I'm with you on that. Will adjust it.
