### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by IvoryMask938** [putnam/binmerge#14]
Downloaded the win64 file. Opened the executable. Just shows an empty command box and crashes in the span of half a second.

**Comment by putnam** [comment]
On windows, command line apps need to be run from a command prompt. If you just double click one, the command is run with no arguments and will usually just print the help or an error and then the program ends. Windows then just closes the window.

Open a command prompt first. Then run it by typing binmerge. You need to be in the same folder as the binary.
