### ISSUE TITLE
Request: Do not add ` (Track %s)` suffix on single track discs on `--split`

### ISSUE THREAD

**Issue by MestreLion** [putnam/binmerge#17]
I've noticed `binmerge` is careful enough to use a leading `0` when there are more than 10 tracks, to match Redump's naming convention. It could go one step further and not add the ` (Track %s)` _at all_ if there is only a single track, so the BIN file has the same name as the CUE file.

Granted, one could argue that this is a no-op, as the output files would be identical to the input ones, so the solution would be simply not to invoke `binmerge` at all. True, but parsing the original CUE to determine if `binmerge` should be bypassed or not is a much more complex pipeline than simply `chdman extractcd ... && binmerge --split ...`, so I believe this "no-op" feature is worth having

**Comment by putnam** [comment]
You're right -- the naming convention stuff in `track_filename` didn't consider the single-track case. Fixed it. Do you mind pulling and testing with your setup? d5f4952

**Comment by MestreLion** [comment]
no need to test, you forgot to interpolate the `prefix` :-P

**Comment by putnam** [comment]
Christ. Thanks 👍

**Comment by putnam** [comment]
623ab1b

**Comment by MestreLion** [comment]
Looks great now, thanks!
