### ISSUE TITLE
"IndexError: list index out of range" on macOS

### ISSUE THREAD

**Issue by mokMan23** [putnam/binmerge#20]
on a MacBookPro9,2 running 10.15.7, i get this error running "--split" with a cdrdao ripped fighters megamix saturn ROM. log below:
`mokman23@Catalina-MBP Downloads % ./binmerge --split fightersmegamix.cue fightersmegamix.bin
[INFO]	Output directory: /Users/mokman23/Downloads
[INFO]	Opening cue: /Users/mokman23/Downloads/fightersmegamix.cue
Traceback (most recent call last):
  File "./binmerge", line 367, in <module>
    if not main():
  File "./binmerge", line 332, in main
    cuesheet = gen_split_cuesheet(args.basename, cue_map[0])
IndexError: list index out of range
`

**Comment by putnam** [comment]
It also looks like incorrect command execution. There is not any reason to append the "fightersmegamix.bin" argument like that. That is the basename of the newly output split track files which is not what you want. You'd end up with a list of files like "fightersmegamix.bin (Track 1).bin" and so on.

Without the cue file I can't really help diagnose the issue but I added an error handler to avoid that output.

**Comment by mokMan23** [comment]
> Can you paste the contents of `fightersmegamix.cue` ? I don't know what generated it but either it's blank or has an unexpected format that I may need to add support for.
>
turns out cdrdao actually outputs TOCs rather than actual cue files, this issue can double as a request to add cdrdao TOC support, but you can just use toc2cue (included with the program) to convert between formats.


> It also looks like incorrect command execution. There is not any reason to append the "fightersmegamix.bin" argument like that. That is the basename of the newly output split track files which is not what you want. You'd end up with a list of files like "fightersmegamix.bin (Track 1).bin" and so on.
> 
> Without the cue file I can't really help diagnose the issue but I added an error handler to avoid that output in [a8c34ae](https://github.com/putnam/binmerge/commit/a8c34ae00af5c215b3276e3113e7de6877424202)
>
my bad, due to the lack of specification i assumed the basename would lack the ".bin" extension like most other CLIs do, and it wasn't working since i made the cue file the same name. i'll change the issue's name to reflect this.

**Comment by putnam** [comment]
Yeah I don't really see widespread use of TOC files, but it sounds like I would be reinventing the wheel to recreate toc2cue when it's already included with the one tool that is creating those TOC files.

> my bad, due to the lack of specification

From the help output:
```
positional arguments:
  cuefile               path to current cue file (bin files are expected in the same dir)
  basename              name (without extension) for your new bin/cue files
```

The output files binmerge writes, especially in split mode, need a basename without an extension because it's writing a cue file and multiple bin files with your basename as a prefix. I don't know how else to put this besides calling it "basename". What do you want it to do differently? I feel like I've seen the term basename used widely... maybe it would be easier to understand at a glance if it were called `prefix`?

**Comment by mokMan23** [comment]
> Yeah I don't really see widespread use of TOC files, but it sounds like I would be reinventing the wheel to recreate toc2cue when it's already included with the one tool that is creating those TOC files.
>
doubtful. it shows that a small minority will have this issue since i'm the first (and will probably be the last) to file an issue like this. most people would just use a program like ImgBurn.
> 
> > my bad, due to the lack of specification
> 
> From the help output:
> 
> ```
> positional arguments:
>   cuefile               path to current cue file (bin files are expected in the same dir)
>   basename              name (without extension) for your new bin/cue files
> ```
> 
> The output files binmerge writes, especially in split mode, need a basename without an extension because it's writing a cue file and multiple bin files with your basename as a prefix. I don't know how else to put this besides calling it "basename". What do you want it to do differently? I feel like I've seen the term basename used widely... maybe it would be easier to understand at a glance if it were called `prefix`?
>
i've never seen a program use "basename" instead of a simple "output", and renaming it "prefix" implies you're appending an existing file rather than creating new ones, and the help file already printed with invalid arguments doesn't explain "basename".
