### ISSUE TITLE
Thanks for making binmerge, is there a binsplit?

### ISSUE THREAD

**Issue by cgarz** [putnam/binmerge#3]
Firstly I must say thanks for making bin merge. Everything I was able to find on Google was windows specific. IsoBuster and the like. Even the answers to people asking about doing it on Linux were "go do it on windows" which I thought was awful. I only found binmerge after deciding to search GitHub specifically.

So thanks a bunch! Binmerge deserves more coverage! =D

One problem though. I would like to be able to return to the Redump.org format with the multiple bin files in order to verify against their dat files. So is there a binsplit?

**Comment by putnam** [comment]
Excellent idea and thanks for the patch. Merged

**Comment by putnam** [comment]
By the way, would you be able to document this change in the README.md file too?

**Comment by cgarz** [comment]
Woops good point forgot about README.md

Added it to the bottom with some example motivations.

Wasn't sure about also mentioning chdman but it's 2nd to none for compression and is becoming more popular these days with the new beetle/medafen support. It's only issue is lack of split bin output. So I figured it might be a common use case.
