### ISSUE TITLE
Will be nice to add 'how to...' run this on windows in the README (for newbies like me)

### ISSUE THREAD

**Issue by Jajuar** [putnam/binmerge#9]
Great work with the binmerge 👍 

I had to google a while until I stumbled upon this:

[How to use binmerge on Windows](https://www.cybdyn-systems.com.au/forum/viewtopic.php?t=3086)

Perhaps, this could be useful in the README for those using Win OS 😀

**Comment by SpamHamwich** [comment]
I would normally say that sort of thing is implied by the fact that it's written in python, but considering the majority of this scripts users will be on windows and may be unfamiliar with coding, it may be useful to many to have examples in the readme. This might have also saved me a couple hours by showing me the basename should NOT include the full path of the output directory, even though it clearly states this on the help page :facepalm:

**Comment by putnam** [comment]
```
-o OUTDIR   output directory. defaults to the same directory as source cue
```
The usage tells you pretty clearly which directory the output goes into. Nobody has ever brought this up in five years and it doesn't affect any specific operating system.

You are more than welcome to submit patches to help Windows users like yourself.

**Comment by putnam** [comment]
I created a release just now that is a standalone Windows binary, so if you're having trouble installing and using Python you can use that now.
